sudo: false
language: ruby
before_install:
  - script/bootstrap
  - export PATH=~/bin:"$PATH"
script: script/test
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
notifications:
  email: false
